spring:
  application:
    name: learning-management-system

  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: Learning Management System
    description: Learning Management System application made with Spring Boot
    version: 0.0.1

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
