spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms-test-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
