services:
  postgres:
    image: postgres:latest
    container_name: postgres-local-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms-test-db
    ports:
      - "5432:5432"
    volumes:
      - lms-local-db:/var/lib/postgresql/data

volumes:
  lms-local-db:
