databaseChangeLog:
  - changeSet:
      id: create-course-settings-table
      author: author
      changes:
        - createTable:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: start_date
                  type: datetime
                  constraints:
                    nullable: false
              - column:
                  name: end_date
                  type: datetime
                  constraints:
                    nullable: false
              - column:
                  name: is_public
                  type: boolean
                  constraints:
                    nullable: false
